sudo: false
dist: trusty

language: python

cache: pip

python:
  - "3.5"
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.6"

notifications:
  email: false

matrix:
  fast_finish: true

install:
  - sudo apt-get -qq update
  - sudo apt-get install pandoc  # for uploading to PyPi
  - pip install coveralls
    # Install Poppler manually for Ubuntu 14.04 on Travis
  - sudo apt-get install build-essential checkinstall
  - wget poppler.freedesktop.org/poppler-0.53.0.tar.xz
  - tar -xf ./poppler-0.53.0.tar.xz
  - cd poppler-0.53.0
  - ./configure
  - make
  - sudo checkinstall -y
  - cd ..
  - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
  - echo "Using LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"

  - pip install -r python-package-requirement.txt
  - python -m spacy download en

before_script:
  - make docs
  - psql -c 'create database parser_test;' -U postgres
  - psql -c 'create database e2e_test;' -U postgres
  - cd tests/e2e/
  - ./download_data.sh
  - cd ../..
  - source ./set_env.sh

script:
  - travis_wait coverage run --source=fonduer setup.py test

after_success:
  - coveralls

deloy:
  provider: pypi
  user: lukehsiao
  password:
    secure: BYpjjgOk4RZohLStyqIlP2UYCOgG76zykvxfNp2wP6ewb5Sf7HPn4BDMst1FCCPBm6ekLlIRAdZJFJp/+IPyakkWeeT/FPM6oqZxeFsa6o0aFdxzHU4qA4aEb03MUpj+7lcQ9WS8x88yyLEjxQuAN31eHNAhVWUfl59ek7Jg2zJ+m/xUmKBrVjPTkrO/PNzJ3AkcKieB/27XM6CVBfi0a+JVBrZUM+nT6WtVAwp9porcOXRj6mma7vzviyo1pIhqQkruHWDeS+iZ890KuKGwRv0QWWz5w04GVC8Yg0bTc/7kY48wHjOGiSajahdM3HjhQ5ekLwP/iUdU6ICTjfj4fHt4EJhv2TOd/P9A39Sp6Q0kUQkhp8/gyz/xBt0DdMx6XXMrUsUkP/tv7aCyRvRmm6mXrpOfODEbecbXTLG6dCdha4RluWfp5cq3Q2iYclskv0o2bwXaOvr6a7fAZO2mlKsZ/EaCJPGhKRbLe03OYo9RWvd9tPgeSrw2kYmOyc3jGuSRIBBC6PFBggK8wBnznkdYq22sI7j8xCqk8Fi/sQ7Hg1PyCIJAWQQgRUJEcMmY8eW30H7dObypORILxijUm50VoPTFcweCbM4kRTSC4+rwZOzTtH4dLGser8i4vg09JjO2iXNyDfFCaeZctTDX+pjTnEqX5wlz6zYhZUgJtwg=
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    python: '3.6' # only deploy once from the latest tested version
