sudo: false
dist: trusty
language: python
cache: pip

python:
- '3.5'
- '3.6'

services:
- postgresql

addons:
  postgresql: '9.6'

notifications:
  email: false

matrix:
  fast_finish: true

install:
- sudo apt-get -qq update
- pip install coveralls
- pip install flake8
- sudo apt-get install build-essential checkinstall
- wget poppler.freedesktop.org/poppler-0.53.0.tar.xz
- tar -xf ./poppler-0.53.0.tar.xz
- cd poppler-0.53.0
- "./configure"
- make
- sudo checkinstall -y
- cd ..
- export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
- echo "Using LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
- make dev  # install package locally for tests
- python -m spacy download en

before_script:
- psql -c 'create database parser_test;' -U postgres
- psql -c 'create database e2e_test;' -U postgres
- cd tests/e2e/
- "./download_data.sh"
- cd ../..
- flake8 fonduer --count --max-line-length=127 --statistics --show-source --ignore=E731,W503,E741,E203

script:
- travis_wait coverage run --source=fonduer -m pytest tests -v -rsXx

after_success:
- coveralls

deploy:
  provider: pypi
  user: lukehsiao
  password:
    secure: ddkakQE29dAbKo362iFHA1kAzPe6GuMV+zP5GkwYsglYgIOY+iYnPWlnZPaxLOkJyGTASOqOVdtRMg9K67kfTBT7h0yBOozZy6rs595cLX7gNLsjKHbciEK1pyebh82wMmiifCqNfwyf/epOqVAPxV8rzzVRw/x9lVMzNZasIpLQ1yVQyGjnAvm/8BIMhTFfN7DbASWpUUFBZDwjqLtHP8HsJLYucd4y7Hle9FqJ+HA7QGS71D+FVbYu16QNG2iwqnKLjYA8xJbNmzDCYUWZW6De89nbddoGmCfqCFXQK+aALpHjpy/vt811313c6sZy97glJmqRsTo7Z/xxmytYpG6+2Tvid1O0BS3AZOOVYEd/JvW3SURWuxdD1eI6LlZL6oAjNraq7h8XbPhyFfAsBXyahfsMA2tLoHqsLP0jnpVqcMzjn8auWGg0qWhNMxMCkMc0SSVY6mqvpQbnj7ntA5JaweCG56BddYqeOiSGtHhK56sGsQw7+CN/2l4GRlgT0FLkRVJBimD2yd2elyJK9r2gePeaD9Ea/Y2xhEIdilTMDSttZMMkwGsZqpY6//KiGGzFfyV66lWJkY6I1btCwB6DaW86lbRFvuqyzDwKbqZUyLdPHiBmoOjtmAtZyaUKQbnffqiGw1w0nu9viR22iF7zQctQ84R/wTq03tiZfco=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    tags: true
    branch: master
    python: '3.6'
